spring:
  profiles:
    # 当前dev环境
    active: dev

---
server:
  port: 7001
  
# dev环境的配置
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka

# Eureka配置
eureka:
  instance:
    # Eureka服务端的示例名字
    hostname: eureka7001.com
  client:
    # 是否向Eureka注册中心注册自己（这个模块本身就是服务器，选择false）
    register-with-eureka: false
    # 表示自己为注册中心，客户端的fetch-registry改为true
    fetch-registry: false
    service-url:    # 监控页面，重写Eureka的默认端口和访问路径
      # 单机：defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群：7001关联7002和7003
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      
      
---
server:
  port: 7001
  
# test环境的配置
spring:
  profiles: test
  application:
    name: springcloud-config-eureka

# Eureka配置
eureka:
  instance:
    # Eureka服务端的示例名字
    hostname: eureka7001.com
  client:
    # 是否向Eureka注册中心注册自己（这个模块本身就是服务器，选择false）
    register-with-eureka: false
    # 表示自己为注册中心，客户端的fetch-registry改为true
    fetch-registry: false
    service-url:    # 监控页面，重写Eureka的默认端口和访问路径
      # 单机：defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群：7001关联7002和7003
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
