spring:
  profiles:
    active: dev

---
server:
  port: 8001

# mybatis
mybatis:
  type-aliases-package: com.run.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml   # mybatis-config配置路径(可用可不用)
  mapper-locations: classpath:mybatis/mapper/*.xml    # mapper路径

# spring
spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      # 注册中心地址为7001~7003
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-privider-dept-8001 # 修改Eureka上面默认的描述信息(status)

# info配置
info:
  # 项目名
  app.name: run-springcloud
  # 公司名
  company.name: WIT-CSFaculty
  
  
---
server:
  port: 8001

# mybatis
mybatis:
  type-aliases-package: com.run.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml   # mybatis-config配置路径(可用可不用)
  mapper-locations: classpath:mybatis/mapper/*.xml    # mapper路径

# spring
spring:
  profiles: test
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      # 注册中心地址为7001~7003
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-privider-dept-8001 # 修改Eureka上面默认的描述信息(status)

# info配置
info:
  # 项目名
  app.name: run-springcloud
  # 公司名
  company.name: WIT-CSFaculty
